# Generated by Django 3.1 on 2020-11-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(help_text='Full name')),
                ('status', models.TextField(help_text='Сandidate status')),
                ('addition_info', models.JSONField(null=True)),
                ('created_timestamp', models.DateTimeField(help_text='Timestamp of creation')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Resume text')),
                ('tags', models.JSONField(null=True)),
                ('created_timestamp', models.DateTimeField(help_text='Timestamp of creation')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(help_text='Timestamp of creation')),
                ('json_scenario', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Task text')),
                ('path', models.TextField(help_text='Path to task documents')),
                ('created_timestamp', models.DateTimeField(help_text='Timestamp of creation')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Vacancy name')),
                ('source_text', models.TextField(help_text='Source text of vacancy')),
                ('transfored_text', models.TextField(help_text='Text of vacancy after transformation')),
                ('created_timestamp', models.DateTimeField(help_text='Timestamp of creation')),
                ('finished_timestamp', models.DateTimeField(help_text='Timestamp of expiration')),
                ('scenario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.scenario')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy2Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Сompliance score')),
                ('created_timestamp', models.DateTimeField(help_text='Timestamp of creation')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.resume')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vacancy')),
            ],
        ),
    ]
