# Generated by Django 3.1.3 on 2020-11-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.FloatField(default=0.0, help_text='Score of resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.TextField(default='', help_text='Resume status'),
        ),
    ]
