# Generated by Django 3.1.3 on 2020-11-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201127_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='path',
        ),
        migrations.AddField(
            model_name='task',
            name='task_file',
            field=models.FileField(default=None, help_text='Path to task documents', null=True, upload_to=''),
        ),
    ]
