# Generated by Django 3.1.3 on 2020-11-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201128_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='finished_timestamp',
            field=models.DateTimeField(help_text='Timestamp of expiration', null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='scenario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.scenario'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.task'),
        ),
    ]
