# Generated by Django 3.1.3 on 2020-11-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201128_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='transfored_text',
            new_name='transformed_text',
        ),
    ]
